### PR TITLE
Minor Python syntax fixes

### PR DESCRIPTION
**Pull request by mujeeb91**

### CODE REVIEW

**Comment by mujeeb91** [comment]
>This screws up the formatting. I don't like this triple quote patch.
No worries, I'll remove the triple quote patch from this PR.

**Comment by mujeeb91** [comment]
> Hmm, this one, I feel like I put the "if iterable:" in there because something broke without it. I'm not a good enough python programmer that I'd know to try that, so I get the feeling I put it in there for a reason. (might be wrong, but... it really feels like I wouldn't have known to put that in there unless something happened that made me look it up and figure it out.)
> 
> Jesus christ github sucks. This comment is in regard to the last patch in the series. "if iterable" is not the same as testing for an "empty iterable". i.e. None vs. empty iterable, here is a demonstration:
> 
> ```
> scameron@wombat ~ $ cat x.py
> x = [];
> y = None;
> 
> 
> for i in x:
> 	print i;
> 
> for i in y:
> 	print i;
> 
> 
> 
> scameron@wombat ~ $ python x.py
> Traceback (most recent call last):
>   File "x.py", line 8, in <module>
>     for i in y:
> TypeError: 'NoneType' object is not iterable
> ```

I thought `get_first` was always getting a list but you're right, it could be `None` too.
How about we change this line,
`words = re.split("[, .]", raw_input("> "))`
to this,
`words = re.split("[, .]", raw_input("> ")) or []`
Doing so will set `words` to [] if the regular expression does not find a match. It will also avoid the need for adding `if iterable:` (which is not good for readability because it adds nesting). What do you think?

**Comment by smcameron** [comment]
> @smcameron to add comment on a specific line you'll need to go to the _Files changed_ tab, hover over the line (this will show a plus icon), clicking on it will open a comment box.

Thanks.  (doubt I'll remember though, I generally prefer patches to pull requests, but for hacktoberfest, whatever.)

**Comment by mujeeb91** [comment]
Ok. I've updated the PR, it only contains the semicolon changes now.

**Pull request merged**
